name: build-test-deploy

on: workflow_dispatch

jobs:
 build-1:
   runs-on: ubuntu-latest
   steps:
     - run: echo "..."
 
 build-2:
   runs-on: ubuntu-latest
   steps:
     - run: echo "..."
 
 build-3:
   runs-on: ubuntu-latest
   steps:
   - name: Sleep for 30 seconds
     uses: jakejarvis/wait-action@master
     with:
       time: '600'
 
 lint:
   runs-on: ubuntu-latest
   needs: [build-2]
   steps:
     - run: echo "..."
 
 unit-test:
   runs-on: ubuntu-latest
   strategy:
    matrix:
      node-version: [4,6,8]
   needs: [build-1]
   steps:
     - run: echo "..."
 
 deploy:
   runs-on: ubuntu-latest
   needs: [lint, unit-test, build-3]
   steps:
     - run: echo "..."
 
