on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: 'Make Artifact'
      run: |
        mkdir -p myArtifacts
        echo hi > myArtifacts/my_file.txt

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: myArtifacts
