name: main
on: [push, workflow_dispatch]
jobs:
  j1:
    steps:
      - run: echo "context ${{ github.ref }}"
      - run: echo "var $GITHUB_REF"
      - run: echo "${{ env.var1 }}"
    runs-on: ubuntu-latest
    env: 
      var1: monkey
  j2:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
#   j3:
#     if: $GITHUB_REF == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Deploying to production server on branch $GITHUB_REF"
