name: need-fail-continue

on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: exit 1 # This will cause job1 to fail
  
  job2:
    needs: [job1]
    if: ${{ always() }} # This makes job2 run even if job1 fails
    runs-on: ubuntu-latest
    steps: 
      - run: echo '...'
  
