name: need-fail-continue

on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: exit 1
        continue-on-error: true
  
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps: 
      - run: echo '...'
  
