name: print pr context

on:
  pull_request:
    types: [labeled]

jobs:
  print context:
    runs-on: ubuntu-latest
    steps:
    - name: print context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: print node id of pr
      env:
        PR: ${{ github.event.pull_request.node_id }}
      run: echo "$PR"
