on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          REPO: ${{ github.repository }}
          NAME: ${{ github.repository.name }}
          NAME2: ${{ github.repository_name }}
          OWNER: ${{ github.repository_owner }}
        run: echo r "$REPO" n "$NAME" n2 "$NAME2" o "$OWNER"
