name: Custom shell

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Display the path
        run: |
          echo "DATE=$(date -d next-monday '+%b %d, %Y')" >> $GITHUB_ENV
          echo "DATE2=$(date -d next-monday '+%V, %Y')" >> $GITHUB_ENV
          echo ${{ env.DATE }}
          echo ${{ env.DATE2 }}
