name: Label issues
on:
  workflow_dispatch
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: zero
        run: exit 0
        continue-on-error: true
      - name: neg
        run: exit -1
        continue-on-error: true
      - name: pos
        run: exit 1
        continue-on-error: true
      - name: str
        run: exit 'cat'
        continue-on-error: true
