name: Python package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python

