name: Python package

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set the value
      run: |
          echo "action_state=yellow" >> $GITHUB_ENV
    - name: Use the value
      run: |
          echo $action_state
