on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          REPO: ${{ github.repository }}
          NAME: ${{ github.repository.name }}
        run: echo "$REPO" "$NAME"
