name: Triage new issues
on:
  issues:
    types:
      - reopened
      - opened
      - labeled

jobs:
  triage_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Label new issues with 'triage'
        uses: andymckay/labeler@master
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          add-labels: 'triage'

  peter-evans:
    name: peter evans comments
    runs-on: ubuntu-latest
    steps:
      
    - name: Create comment peter-evans
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: 1
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:

    - name: Create comment peter-evans with issue numb from event
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.id }}
        body: |
          Comment 2
          
  b4b4r07-comment:
    name: b4b4r07 comment
    runs-on: ubuntu-latest
    steps:
    - name: b4b4r07 comment hardcode
      uses: b4b4r07/action-github-comment@v1
      with:
        body: |
          Comment 3
        number: 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG: trace
    - name: b4b4r07 comment
      uses: b4b4r07/action-github-comment@v1
      with:
        body: |
          Comment 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG: trace


