# name: label on move
# on:
#   project_card:
#     types:
#       - moved
# jobs:
#   label_on_move:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Label issues
#         uses: andymckay/labeler@1.0.2
#         with:
#           repo-token: '${{ secrets.GITHUB_TOKEN }}'
#           add-labels: 'bug'

name: issue-automation

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  project_card:
    types: [moved]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "bug"

# name: board
# on:
#   issues:
#     types: [assigned]
#   project_card:
# jobs:
#   Add_New_Issue_To_Project:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
#       with:
#         action-token: "${{ secrets.GITHUB_TOKEN }}"
#         project-url: "https://github.com/skedwards88/test-area-2/projects/1"
#         column-name: "In Progress"
#     - uses: hmarr/debug-action@master
