name: Label issues
on:
  workflow_dispatch
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$COMMAND_CONTEXT"
      - name: pring
        run: echo "known $GITHUB_REF job $GITHUB_JOB"

