name: Custom shell

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Display the path
        run: |
          echo "DATE=$(date -d+1w '+%V, %Y')" >> $GITHUB_ENV
          echo ${{ env.DATE }}

