name: print
on: push
env: 
  continue: true
  time: 3
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - continue-on-error: ${{ fromJson(env.continue) }}
      timeout-minutes: ${{ fromJson(env.time) }}
      run: echo ...
